### ISSUE TITLE
block not dropping on break.

### ISSUE THREAD

**Issue by Terminus1210** [ManaStar/compat-o-plenty#11]
The galanos blocks that you craft are not dropping when you break them, with silk touch or otherwise.
Edit: looking through the files, its just missing the loot table to drop, I think

**Comment by ManaStar** [comment]
Am in the middle of converting all json stuff to datagen, will absolutely be sure not to miss those this time!

**Comment by ManaStar** [comment]
This will be left open until that update releases

**Comment by Terminus1210** [comment]
alright, thank you so much!
