### ISSUE TITLE
[Suggestion] Add Friends&Foes compatibility for its variant wood beehives

### ISSUE THREAD

**Issue by DarthCaesium** [ManaStar/compat-o-plenty#13]
This shouldn't be too difficult as you already have variant wood beehives for Buzzier Bees.

**Comment by ManaStar** [comment]
Am very late but I won't be doing this, I don't think it's worthwhile to maintain 2 different sets of beehives honestly.

**Comment by DarthCaesium** [comment]
I did not suggest maintaining two different sets, just to have code that says: "This person is using Buzzier Bees or Friends and Foes? Let's give them the beehive variants." I did not mean that you should maintain two different sets of beehives.
