### ISSUE TITLE
Trapped Chests redstone logic incorrectly implemented

### ISSUE THREAD

**Issue by Kenpari** [ManaStar/compat-o-plenty#14]
It looks like trapped chests have some issues with their redstone implementation. If you attach a wire to the side of a trapped chest variant and open it, it will not power the adjacent redstone wire. Vanilla trapped chests will output a redstone signal to the attached wire in this circumstance.

Also, there is additional odd behavior with hoppers. If you place a trapped chest on top of a hopper (classic locking mechanism to prevent items being sucked through the hopper while you're putting things in the chest, to avoid misplaced items), and open the trapped chest, the hopper should lock while the chest is open, then unlock immediately after the chest is closed. Variant trapped chests will indeed lock the hopper, but the hopper will stay locked after closing for a long period of time. I'm not exactly sure how long this period of time is, but it is significantly longer than it should be.

There are perhaps other redstone implementation issues with the trapped chests, but these were the most apparent I found in my limited testing.

**Comment by ManaStar** [comment]
This would be an issue with our library: Blueprint. I would send this issue their way if you want this fixed!
