### ISSUE TITLE
Farmer's Delight Integrations Not Showing Up

### ISSUE THREAD

**Issue by theHoodaloo** [ManaStar/compat-o-plenty#16]
I have Blueprint, Biomes O Plenty, and Farmer's Delight on my Curseforge 1.16.5 modpack, and the Farmer's delight integrations, being the cabinet types, seem to be missing.

**Comment by ManaStar** [comment]
Please search for pantries instead of cabinets in the 1.16 version and get back to me on that!

**Comment by theHoodaloo** [comment]
Yep, that was the problem, I would recommend you change the terminology on the curseforge to pantries instead of cabinets.

**Comment by ManaStar** [comment]
The 1.16.5 version is no longer officially supported, so it wouldn't make much sense to change the terminology to the older name. But since this was resolved I am going to close it now!
