### ISSUE TITLE
Instant crash on seeing rainbow birch hedges or carpet

### ISSUE THREAD

**Issue by deputydevil** [ManaStar/compat-o-plenty#17]
https://pastebin.com/jEjh1tGd

**Comment by SmallSansSerif** [comment]
I also have this client crash with rainbow birch hedges.
[crash-2022-07-07_20.00.58-client.txt](https://github.com/ManaStar/compat-o-plenty/files/9068059/crash-2022-07-07_20.00.58-client.txt)

**Comment by ManaStar** [comment]
On it now!

**Comment by Nataly171** [comment]
It just happened to me with the Rainbow Birch Leaf Carpet. I placed it and it was invisible and gave an error message in chat, and when I tried to break it, the game crashed.
[Here's the crash report](https://github.com/ManaStar/compat-o-plenty/files/9238158/crash-2022-08-01_19.27.14-client.txt)

**Comment by Zelerity** [comment]
I believe this (issue) should be reopened. Rendering the Rainbow Birch Leaf Carpet and/or Rainbow Birch Hedge essentially crashes the game - it does not respond, and you have to ALT F4.

**Comment by ManaStar** [comment]
Make sure to use the latest beta release of BOP for 1.18.2 otherwise you will crash!!!
