### ISSUE TITLE
[Bug] Rainbow Birch Hedge and Leaf Carpet crash

### ISSUE THREAD

**Issue by Zelerity** [ManaStar/compat-o-plenty#20]
Unable to provide crash report since the client just hangs and has to be forcefully closed.

**Comment by ManaStar** [comment]
This is a solved issue to my understanding, unless you can verify that this is somehow still happening in the latest COP version then I will have to close this.

**Comment by ManaStar** [comment]
Have realized that you are most likely relying on an older version of BOP, make sure to use the latest 1.18.2 beta or things won't go too well!
