### ISSUE TITLE
[BUG] Unable to craft BOP variant items (1.18.2)

### ISSUE THREAD

**Issue by Zzzjuul** [ManaStar/compat-o-plenty#22]
Recently added Woodworks 1.18.2 - 1.0.0 and now the crafting recipes for the BOP chest, ladders and beehives are missing and I'm unable craft them. 

Using Compat O plenty 1.18.2 - 1.5.4, Blueprint 1.18.2 5.4.7, Woodworks 1.18.2 - 1.0.0 and BOP 1.18.2 - 16.0.0.134

**Comment by ManaStar** [comment]
Quark automatically disables its wood variant blocks when alongside Woodworks. Since our blocks are tied to that same action they are also disabled. HOWEVER I do have plans to convert all of our wood blocks to Woodworks compat so this will be resolved soon enough!

**Comment by ManaStar** [comment]
Fixed in latest build of 1.18.2
