### ISSUE TITLE
1.19.2: Only BOP cabinets and beehives showing

### ISSUE THREAD

**Issue by Maltshakes** [ManaStar/compat-o-plenty#25]
Even with Woodworks, Biomes O Plenty, and Farmer's Delight installed, only the beehive and cabinets are showing as accessible. No BOP signs, ladders, chests, signs, or bookshelves are loaded in. 

![2022-11-09 19_04_03-Minecraft_ 1 19 2 - Singleplayer](https://user-images.githubusercontent.com/76584081/200906274-77d6e1a7-58d9-44a6-a90e-477dbaa23add.png)

**Comment by ManaStar** [comment]
Same cause as #24, so I will be closing this due to being a duplicate. (I do have the fix ready however so yay!)
