### ISSUE TITLE
No cabinets version has a few farmers delight tags and items that show up in the log as invalid recipes

### ISSUE THREAD

**Issue by zachsai** [ManaStar/compat-o-plenty#3]
https://gist.github.com/WelpSTudent/74efdc2fe32323185a44a184b02b5a12

You can see there is some farmers delight stuff in the no cabinets version, if you could clean up that version and remove the stuff that shouldnt be there, it could help in the future, thanks!

**Comment by ManaStar** [comment]
Shoot I thought I got those, will get that fixed asap!
