### ISSUE TITLE
Boatload Missing Textures

### ISSUE THREAD

**Issue by aveinzero** [ManaStar/compat-o-plenty#32]
![image](https://user-images.githubusercontent.com/99594631/220929380-e7438597-f848-45a1-9521-72f07e005c6d.png)
All boats with furnaces have missing texture when fueled with coal (oak boat on the left)

**Comment by ManaStar** [comment]
Am very late to this but what version of both minecraft and boatload are you using?

**Comment by ManaStar** [comment]
Scratch that, am just missing the on texture for every single boat...

**Comment by Telezhka-the-First** [comment]
So, will you this that issue? Forge 1.19.2 version of your mod also has this problem.

**Comment by ManaStar** [comment]
I have this issue fixed in my build, will have it uploaded really soon!

(Will be closed once I've uploaded it)

**Comment by Telezhka-the-First** [comment]
> I have this issue fixed in my build, will have it uploaded really soon!
> 
> (Will be closed once I've uploaded it)

So, did you fix it? If so, could you release a new version of the mod? Both Modrinth and Curseforge last version is from 2022...
