### ISSUE TITLE
[BUG] RecipeManager

### ISSUE THREAD

**Issue by Relaxing9** [ManaStar/compat-o-plenty#35]
Hello I am getting an error message when starting my server:
Here's my startup log: [https://paste.gg/p/anonymous/3b8d648df25c4f03986783d51425144e](https://paste.gg/p/anonymous/3b8d648df25c4f03986783d51425144e)

A good chunk of my startup log is Recipe Manager errors from Compat-o-Plenty.

Compat-o-Plenty Version: Compat O' Plenty (compatoplenty v.1.18.2-2.0.1)
Server Type: Magma version 1.18.2-1d566d5a (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge Version 40.2.1)

**Comment by ManaStar** [comment]
I think this has to be the biggest oversight of all time on my end to be honest, will be resolved soon!

**Comment by Relaxing9** [comment]
Thanks would heavily appreciate it!

**Comment by Relaxing9** [comment]
Seems to be resolved in supplementaries v.1.18.2-1.5.17. I appreciate this being fixed!

**Comment by Relaxing9** [comment]
Lol I confused myself please disregard my closing & reopening.
