### ISSUE TITLE
Blocks missing breaking tool

### ISSUE THREAD

**Issue by mouse0270** [ManaStar/compat-o-plenty#4]
I can't tell you exactly how many are missing their breaking tool, but I can tell you at least Chests are.

For example, if a normal chest is set to break with a axe, so using that tool will break it faster then using anything else. Chests added by this mod, do not have this set.

**Comment by ManaStar** [comment]
I must have forgot chests and trapped chests in the port, good catch!

**Comment by mouse0270** [comment]
No worries, just wanted to point it out. So many mods seem to miss this little thing.
