### ISSUE TITLE
References remain to removed Biomes 'O Plenty Signs [1.18.1-1.2.1]

### ISSUE THREAD

**Issue by sdarkwell** [ManaStar/compat-o-plenty#5]
**Hello,**

While using KubeJS, it detected warnings generated by your mod–there still appears to be references to Compat-O-Plenty replacements for Biomes 'O Plenty Signs (a cutting recipe, the en_lang file).

**Hope this is helpful! Thank you and be well. :)**
\- S.

**Comment by ManaStar** [comment]
Appreciated, will be closing this quick!
