### ISSUE TITLE
[Suggestion] Compat with Lepton

### ISSUE THREAD

**Issue by Matthysse** [ManaStar/compat-o-plenty#8]
Hello!
I would love to see compatibility between Lepton Forge ([https://www.curseforge.com/minecraft/mc-mods/lepton](url)) and Biomes'O'Plenty.
The mod has compat for the abnormals mods, and adds stairs and slabs for the stripped wood variants for example. The author doesn't want to add BOP compat himself (https://github.com/Eltrut-Co/Lepton-Forge/issues/26).

Would be really awesome!
Thanks for your amazing work on the mod!

**Comment by ManaStar** [comment]
Absolutely haven't checked this in a while, is on my planned list am just not sure when I will get to it!
